insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (29862, 'Wirodayan', 1, 'Center', 'Hanover');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (84229, 'Thạnh Hóa', 91, 'Circle', 'Maple');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (11063, 'Orsk', 24, 'Crossing', 'Independence');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (57589, 'Haarlem', 23, 'Point', 'Pleasure');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (72748, 'Singa', 100, 'Pass', 'Clarendon');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (18817, 'Altavista', 92, 'Lane', '5th');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (59345, 'Czerniewice', 70, 'Lane', 'American');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (52412, 'Grangwav', 79, 'Court', 'Summer Ridge');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (74544, 'Mollas', 87, 'Street', 'Brickson Park');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (25069, 'Colorado Springs', 89, 'Hill', 'Cottonwood');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (81012, 'Cajamarca', 34, 'Crossing', 'Center');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (68044, 'Jicomé', 88, 'Drive', 'Del Mar');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (58545, 'Dayr as Sūdān', 57, 'Way', 'New Castle');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (37944, 'Gózd', 65, 'Circle', 'Brentwood');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (84520, 'Maojiagang', 8, 'Hill', 'Rusk');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (58694, 'Kajanan', 10, 'Trail', 'Mifflin');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (61654, 'Nossa Senhora do Socorro', 99, 'Junction', 'Sachtjen');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (26725, 'Lilla Edet', 14, 'Alley', 'Sheridan');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (59526, 'Maubeuge', 13, 'Place', 'Chive');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (14467, 'Kohtla-Järve', 57, 'Drive', 'Norway Maple');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (21684, 'Ameixoeira', 90, 'Pass', 'Logan');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (34001, 'Changzhi', 55, 'Junction', 'Russell');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (39238, 'Mtubatuba', 21, 'Place', 'Lunder');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (90769, 'Satowebrang', 2, 'Street', 'Moulton');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (91989, 'Tosno', 12, 'Drive', 'Autumn Leaf');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (18159, 'Tha Tako', 46, 'Lane', 'Sloan');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (87566, 'Fukiage-fujimi', 26, 'Center', 'Morning');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (11335, 'Jun’an', 63, 'Circle', 'Clyde Gallagher');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (87591, 'Prislonica', 52, 'Center', 'Welch');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (53509, 'Rantepang', 74, 'Plaza', 'Russell');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (47389, 'Carmo do Paranaíba', 63, 'Center', 'Nelson');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (77254, 'La Ceja', 80, 'Pass', 'Fair Oaks');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (70928, 'Poykovskiy', 84, 'Alley', 'Susan');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (89991, 'Burgos', 32, 'Plaza', 'Paget');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (25184, 'Miyazaki-shi', 36, 'Avenue', 'Birchwood');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (51473, 'Xinxu', 42, 'Center', 'Havey');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (50626, 'Tangxian', 84, 'Pass', 'Lake View');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (20059, 'A Yun Pa', 67, 'Avenue', 'Pearson');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (19532, 'Hacıqabul', 93, 'Center', 'Welch');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (81390, 'Brejieira', 77, 'Hill', 'Pierstorff');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (71564, 'Ishii', 29, 'Junction', 'Fulton');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (10004, 'Yoshkar-Ola', 31, 'Place', '5th');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (72304, 'Regimin', 97, 'Hill', 'Onsgard');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (35182, 'Shizuishan', 74, 'Way', 'Schmedeman');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (17976, 'Motong', 3, 'Way', 'Sachs');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (40199, 'Alvide', 65, 'Circle', 'Haas');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (60040, 'Wapno', 27, 'Trail', 'Summerview');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (82136, 'Nanxing', 51, 'Street', 'Schlimgen');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (17077, 'Tha Bo', 35, 'Center', 'Main');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (66555, 'Parreira', 6, 'Trail', 'Iowa');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (37760, 'Boac', 4, 'Circle', 'Dottie');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (46337, 'Lypnyazhka', 38, 'Center', 'Sachs');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (32337, 'Vyshhorod', 24, 'Center', 'Sunnyside');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (25011, 'Donim', 57, 'Alley', 'Welch');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (92685, 'Cansolungon', 53, 'Road', 'Quincy');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (69573, 'Old Shinyanga', 89, 'Alley', 'Westend');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (91189, 'Las Vegas', 5, 'Park', 'Bartillon');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (38912, 'Liborina', 1, 'Junction', 'Clove');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (47306, 'Effium', 29, 'Avenue', 'Debra');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (78095, 'Lhabupu', 24, 'Crossing', 'Continental');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (47228, 'Chuantang', 18, 'Circle', 'Mesta');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (64830, 'Phoenix', 27, 'Parkway', 'Bartillon');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (36201, 'Kuala Lumpur', 46, 'Court', 'Dryden');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (46895, 'Podedwórze', 26, 'Hill', 'Muir');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (39259, 'København', 37, 'Lane', 'Harper');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (16083, 'Strogino', 80, 'Park', 'David');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (13915, 'Kosai-shi', 71, 'Pass', 'Pearson');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (11121, 'Sumberkemuning', 62, 'Park', 'Dahle');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (56590, 'Asarum', 67, 'Place', 'Manufacturers');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (77913, 'Palanit', 72, 'Center', 'Sunnyside');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (53165, 'Senador Canedo', 49, 'Court', 'Fuller');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (34330, 'Presidente Médici', 67, 'Junction', 'Declaration');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (80559, 'Sayán', 16, 'Road', 'Duke');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (18646, 'Ferraz de Vasconcelos', 25, 'Crossing', 'Hermina');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (79580, 'Iłowa', 30, 'Pass', 'Melby');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (77821, 'Chambar', 53, 'Place', 'Di Loreto');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (43662, 'Dongting', 9, 'Way', 'Morrow');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (23921, 'Qingzhou', 82, 'Trail', 'Kinsman');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (31536, 'Krapina', 79, 'Place', 'Upham');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (29499, 'Monte Aprazível', 82, 'Way', 'Shoshone');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (28669, 'Sinabang', 81, 'Point', 'Bellgrove');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (70872, 'Maying', 3, 'Crossing', 'Havey');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (28809, 'Velenje', 2, 'Circle', 'Shoshone');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (46550, 'Khilok', 81, 'Place', 'Mayfield');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (86903, 'Usagara', 85, 'Way', 'Crowley');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (50380, 'Utrecht (stad)', 80, 'Crossing', 'Cottonwood');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (40096, 'Jinhaihu', 38, 'Crossing', 'Schurz');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (14001, 'Peñal', 51, 'Lane', 'Harbort');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (87722, 'Ribeiro', 26, 'Trail', 'Park Meadow');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (78766, 'Tanalt', 27, 'Place', 'Forster');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (31069, 'Xibër-Murrizë', 43, 'Avenue', 'Miller');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (44090, 'Chancay', 37, 'Plaza', 'Larry');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (33258, 'Xinyan', 41, 'Place', 'Walton');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (57742, 'Paris 13', 98, 'Hill', 'Arrowood');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (32932, 'Wasogolo', 45, 'Crossing', 'Oriole');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (93862, 'Lianrao', 87, 'Junction', 'Farmco');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (75552, 'Kubachi', 40, 'Crossing', 'Heffernan');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (92845, 'Riyom', 46, 'Court', 'Farmco');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (52481, 'Xiaba', 85, 'Trail', 'Northland');
insert into adresse (codePostal, ville, numero, TypeVoie, NomVoie) values (63922, 'Tiyuguan', 96, 'Center', 'Farragut');
