insert into marque (designation) values ('3 CONCEPT EYES LIQUID FOUNDATION LACE BEIGE');
insert into marque (designation) values ('Sleep Aid');
insert into marque (designation) values ('Extra Strength Pain Reliever');
insert into marque (designation) values ('MELOXICAM');
insert into marque (designation) values ('Glycopyrrolate');
insert into marque (designation) values ('simvastatin');
insert into marque (designation) values ('3-RAGWEED MIX, GIANT/SHORT/WESTERN POLLEN');
insert into marque (designation) values ('Arnica Aurum Equisetum');
insert into marque (designation) values ('Freshscent Anti-Perspirant Deodorant');
insert into marque (designation) values ('Misoprostol');
insert into marque (designation) values ('H-Acne Formula');
insert into marque (designation) values ('Itraconazole');
insert into marque (designation) values ('Fluoxetine');
insert into marque (designation) values ('Maximum Strength Heartburn Relief 150');
insert into marque (designation) values ('Heparin Sodium');
insert into marque (designation) values ('70%');
insert into marque (designation) values ('Cefuroxime');
insert into marque (designation) values ('Midazolam HCl');
insert into marque (designation) values ('Buspirone Hydrochloride');
insert into marque (designation) values ('Vespa crabro ex animale 6 Special Order');
insert into marque (designation) values ('Methimazole');
insert into marque (designation) values ('Valsartan and Hydrochlorothiazide');
insert into marque (designation) values ('ACNEFORCE');
insert into marque (designation) values ('METFORMIN HYDROCHLORIDE');
insert into marque (designation) values ('Oxybutynin Chloride');
insert into marque (designation) values ('Amlodipine Besylate and Benazepril Hydrochloride');
insert into marque (designation) values ('50% Rubbing');
insert into marque (designation) values ('Oxazepam');
insert into marque (designation) values ('Motion Sickness');
insert into marque (designation) values ('Prazosin Hydrochloride');
insert into marque (designation) values ('Amitriptyline Hydrochloride');
insert into marque (designation) values ('Metformin Hydrochloride');
insert into marque (designation) values ('Lansoprazole');
insert into marque (designation) values ('VIVITROL');
insert into marque (designation) values ('equaline pain relief');
insert into marque (designation) values ('NUJEVI ACNE');
insert into marque (designation) values ('Ropinirole Hydrochloride');
insert into marque (designation) values ('Promethazine Hydrochloride');
insert into marque (designation) values ('Loratadine');
insert into marque (designation) values ('TopCare Aspirin');
insert into marque (designation) values ('OXYGEN');
insert into marque (designation) values ('Fenofibrate');
insert into marque (designation) values ('ZENATANE');
insert into marque (designation) values ('Cefazolin');
insert into marque (designation) values ('LISINOPRIL AND HYDROCHLOROTHIAZIDE');
insert into marque (designation) values ('Gas Relief');
insert into marque (designation) values ('All Day Allergy');
insert into marque (designation) values ('Bupivacaine Hydrochloride');
insert into marque (designation) values ('Dandruff');
insert into marque (designation) values ('Cephalexin');
